export function setUser (state, data) {
  if (typeof data === 'object') {
    state.user = { ...data }
  } else {
    state.user = data
  }
}

export function setPermissions (state, data) {
  state.roles = data
}

export function teste (state) {
  for (let x = 0; x < 10000; x++) {
    state.teste2.nestedArray.push('skfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasfskfnaskfnasfnaslkfnasklfnasklfnasklfnklasf')
  }
}
